### ISSUE TITLE
[Question] 请问wails dev时能否直接调试frontend？

### ISSUE THREAD

**Issue by cxt90730** [misitebao/wails-template-vue#15]
#### 3. What are your problems? | 您遇到了什么问题？
wails dev时修改frontend代码（譬如css），无法直接看到期望结果
#### 4. What is your expected outcome? | 您期望的结果是怎样的？
修改frontend代码，直接看到期望结果

**Comment by misitebao** [comment]
@cxt90730 
目前是不可以的，目前的`wails dev`还是需要编译打包前端资源到`dist`目录，但是并不能提供类似前端脚手架的`npm run dev`的效果，我现在正在考虑加入这个功能，但是还存在一些问题，可以关注模板新版本的发布，下个小版本会提供这一功能，目前问题还需要`wails`的支持。
