### ISSUE TITLE
why not use vite to build a front-end vue project?

### ISSUE THREAD

**Issue by crushonyou18** [misitebao/wails-template-vue#2]
@misitebao 
Why not use vite to build front-end vue projects, vite builds faster, can improve development efficiency and improve development experience.

**Comment by misitebao** [comment]
> @misitebao
Because the wails front-end rendering engine (webview2 is used on windows) does not support esmodule.

**Comment by misitebao** [comment]
> @misitebao
> Why not use vite to build front-end vue projects, vite builds faster, can improve development efficiency and improve development experience.

Because the wails front-end rendering engine (webview2 is used on windows) does not support esmodule.
