### ISSUE TITLE
[Bug]Error on build: can't find vue.runtime.esm-bundler.js

### ISSUE THREAD

**Issue by MichaelHipp** [misitebao/wails-template-vue#28]
### 1. Your usage scenarios? | 您使用的场景？

Windows Home x32, building a simple app for in-house use.

### 2. What did you do? | 您做了什么操作？

Created a new project using:
   wails init -n pospay -t https://github.com/codydbentley/wails-vite-vue-ts

cd into project, run wails build

### 3. What are your problems? | 您遇到了什么问题？

Build fails with this error:
`
 PS Z:\dev\pospay> wails build
Wails CLI v2.0.0-beta.34

App Type:               desktop
Platforms:              windows/386
Compiler:               C:\Program Files\Go\bin\go.exe
Build Mode:             Production
Skip Frontend:          false
Compress:               false
Package:                true
Clean Build Dir:        false
LDFlags:                ""
Tags:                   []

Building target: windows/386
----------------------------
  - Installing frontend dependencies: Done.
  - Compiling frontend:
    > pospay@0.1.0 build
    > vite build

    vite v2.6.2 building for production...
    transforming...
    ✓ 3 modules transformed.

    [vite:load-fallback] Could not load /vmware-host/Shared Folders/dev/pospay/frontend/node_modules/vue/dist/vue.runtime.esm-bundler.js (imported by src\main.ts): ENOENT: no such file or directory, open 'Z:\vmware-host\Shared Folders\dev\pospay\frontend\node_modules\vue\dist\vue.runtime.esm-bundler.js'
    error during build:
    Error: Could not load /vmware-host/Shared Folders/dev/pospay/frontend/node_modules/vue/dist/vue.runtime.esm-bundler.js (imported by src\main.ts): ENOENT: no such file or directory, open 'Z:\vmware-host\Shared Folders\dev\pospay\frontend\node_modules\vue\dist\vue.runtime.esm-bundler.js'

Error: exit status 1

ERROR: exit status 1

`

### 4. What is your expected outcome? | 您期望的结果是怎样的？

Successful build for Windows

**Comment by misitebao** [comment]
You are not using this project.
